packages: []

catalog:
  '@undp-data/style-switcher': ^2.0.15
  maplibre-gl: ^5.7.0
  sass: ^1.91.0
  terra-draw: ^1.13.0
  terra-draw-maplibre-gl-adapter: ^1.1.2

catalogs:
  build:
    '@nuxt/devtools': ^2.6.3
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.0.3
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.5.0
    '@unocss/nuxt': ^66.5.0
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.8.0
    nuxt: ^4.0.3
    unocss: ^66.5.0
    unplugin: ^2.3.10
    vite: ^7.1.3
  dev:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.9.2
    vue-tsc: ^3.0.6
  frontend:
    '@vueuse/core': ^13.8.0
    pinia: ^3.0.3
    vue: ^3.5.20
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/twemoji': ^1.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
